export const services = [
    {
        name: "Pedicure",
        image: "/images/pedicure.jpg",
        options: [
            { name: "The Essentials", price: "$32", time: "35 mins" },
            { name: "Comfort & Care", price: "$40", time: "40 mins" },
            { name: "Milk & Honey Renewal", price: "$47", time: "45 mins" },
            { name: "Lavender Serenity Spa", price: "$55", time: "50 mins" },
            { name: "The Ultimate Jelly Spa", price: "$68", time: "60 mins" },
            { name: "The Glow-Up Experience (Special)", price: "$98" }, 
        ],
    },
    {
        name: "Manicure",
        image: "/images/manicure.jpg",
        options: [
            { name: "The Essentials", price: "$20", time: "25 mins" },
            { name: "Gel Manicure", price: "$33", time: "40 mins" },
            { name: "Milk and Honey Silk Manicure", price: "$35", time: "50 mins" },
            { name: "Hand-to-Toe Harmony (Combo)", price: "$48", time: "60 mins" },
        ],
    },
    {
        name: "Acrylic",
        image: "/images/acrylic.jpg",
        options: [
            { name: "Full Set", price: "$45+" },
            { name: "Refill", price: "$35+" },
            { name: "Overlay", price: "$40" },
            { name: "Pink & White Full Set", price: "$48" },
            { name: "Pink & White Refill", price: "$38" },
            { name: "Color Powder", price: "$42+" },
            { name: "Ombre (two colors)", price: "$45" },
        ],
    },
    {
        name: "Dipping Powder",
        image: "/images/dip-powder.jpg",
        options: [
            { name: "Dipping Powder", price: "$45+" },
            { name: "Pink & White", price: "$45+" },
            { name: "French Dip", price: "$40+" },
            { name: "Overlay", price: "$40" },
            { name: "Longer Length", price: "$5+" },
        ],
    },
    {
        name: "Gel Builder / BIAB / GELX",
        image: "/images/gel-builder.jpg",
        options: [
            { name: "Gel Builder Full Set", price: "$58+" },
            { name: "Gel Builder Refill", price: "$45+" },
            { name: "BIAB Full Set", price: "$55+" },
            { name: "BIAB Refill", price: "$48+" },
            { name: "BIAB Overlay", price: "$42" },
            { name: "GELX Full Set", price: "$55+" },
            { name: "Tap Gel Full Set", price: "$55" },
            { name: "Tap Gel Refill", price: "$48" },
        ],
    },
    {
        name: "Enhancements & Add-Ons",
        image: "/images/nail-art.jpg",
        options: [
            { name: "Shellac / Gel Polish", price: "$15" },
            { name: "Chrome Finish", price: "$15" },
            { name: "Cat Eye", price: "$10" },
            { name: "Nail Art (custom)", price: "Priced by Design" },
            { name: "Paraffin Wax (hands/feet)", price: "$7–$10" },
            { name: "Hot Stone", price: "$10" },
            { name: "Removal (Acrylic/GelX)", price: "$15" },
            { name: "Removal (Dip/Shellac)", price: "$10" },
        ],
    },
    {
        name: "Lash & Beauty Bar",
        image: "/images/lashes.jpg",
        options: [
            { name: "Classic Full Set", price: "$95" },
            { name: "Refill (3 weeks)", price: "$65" },
            { name: "Cluster Lashes", price: "$35" },
            { name: "Strip Lashes", price: "$20" },
            { name: "Eyebrows Wax", price: "$12" },
            { name: "Full Face Wax", price: "$35" },
            { name: "Chin", price: "$8" },
            { name: "Underarms", price: "$22" },
            { name: "Upper Lip", price: "$10" },
        ],
    },
    {
        name: "Little Princess (12 & Under)",
        image: "/images/kids-nails.jpg",
        options: [
            { name: "Polish Hands", price: "$10" },
            { name: "Polish Feet", price: "$12" },
            { name: "Manicure & Pedicure Combo", price: "$30" },
        ],
    },
];